[I 12:15:09.988 NotebookApp] Serving notebooks from local directory: /home/users/zg78/adver_ml
[I 12:15:09.989 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 12:15:09.989 NotebookApp] http://linux48:8881/?token=e9cd48b7f3066cfabfc407ca98140ffc67e07a938ac6be32
[I 12:15:09.989 NotebookApp]  or http://127.0.0.1:8881/?token=e9cd48b7f3066cfabfc407ca98140ffc67e07a938ac6be32
[I 12:15:09.989 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:15:09.997 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/users/zg78/.local/share/jupyter/runtime/nbserver-16845-open.html
    Or copy and paste one of these URLs:
        http://linux48:8881/?token=e9cd48b7f3066cfabfc407ca98140ffc67e07a938ac6be32
     or http://127.0.0.1:8881/?token=e9cd48b7f3066cfabfc407ca98140ffc67e07a938ac6be32
[I 12:15:38.263 NotebookApp] 302 GET / (152.3.140.46) 1.020000ms
/home/users/zg78/_conda/envs/base_torch/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 12:15:44.967 NotebookApp] Notebook backdoor/test_pipeline.ipynb is not trusted
[I 12:15:45.244 NotebookApp] Kernel started: b6648284-7ed9-465f-91a4-5060923db094, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7f83fe29a908>()
handle: <Handle <TaskStepMethWrapper object at 0x7f83fe29a908>()>
Traceback (most recent call last):
  File "/home/users/zg78/_conda/envs/base_torch/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
/home/users/zg78/_conda/envs/base_torch/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[W 12:16:58.065 NotebookApp] Notebook backdoor/test_pipeline.ipynb is not trusted
[W 12:17:25.087 NotebookApp] Notebook baseline/test_pipeline.ipynb is not trusted
[I 12:17:25.284 NotebookApp] Kernel started: 3cf707c7-4027-4a56-ab78-bdcf12f9612a, name: python3
[I 12:17:45.294 NotebookApp] Saving file at /backdoor/test_pipeline.ipynb
[I 12:19:45.296 NotebookApp] Saving file at /backdoor/test_pipeline.ipynb
[I 12:21:46.030 NotebookApp] Saving file at /backdoor/test_pipeline.ipynb
[I 12:23:46.018 NotebookApp] Saving file at /backdoor/test_pipeline.ipynb
[I 12:37:59.821 NotebookApp] Saving file at /backdoor/test_pipeline.ipynb
[I 12:38:00.987 NotebookApp] Saving file at /baseline/test_pipeline.ipynb
[W 12:38:00.987 NotebookApp] Notebook baseline/test_pipeline.ipynb is not trusted
