[I 17:17:31.537 NotebookApp] Serving notebooks from local directory: /home/users/bc272/ahahahaha/fbchan
[I 17:17:31.538 NotebookApp] Jupyter Notebook 6.4.3 is running at:
[I 17:17:31.538 NotebookApp] http://gpu-compute3:8882/?token=d07afc29d128cd9d131f15878d95f1ce5fc52a1fe4736326
[I 17:17:31.538 NotebookApp]  or http://127.0.0.1:8882/?token=d07afc29d128cd9d131f15878d95f1ce5fc52a1fe4736326
[I 17:17:31.538 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:17:31.547 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/users/bc272/.local/share/jupyter/runtime/nbserver-16003-open.html
    Or copy and paste one of these URLs:
        http://gpu-compute3:8882/?token=d07afc29d128cd9d131f15878d95f1ce5fc52a1fe4736326
     or http://127.0.0.1:8882/?token=d07afc29d128cd9d131f15878d95f1ce5fc52a1fe4736326
/home/users/bc272/anaconda3/envs/base_torch/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 17:19:24.732 NotebookApp] Kernel started: d6897198-4ca2-433f-b270-215887add16f, name: python3
ERROR:asyncio:Exception in callback <TaskStepMethWrapper object at 0x7f502ccae588>()
handle: <Handle <TaskStepMethWrapper object at 0x7f502ccae588>()>
Traceback (most recent call last):
  File "/home/users/bc272/anaconda3/envs/base_torch/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
KeyError: <_UnixSelectorEventLoop running=True closed=False debug=False>
/home/users/bc272/anaconda3/envs/base_torch/lib/python3.6/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 17:20:26.458 NotebookApp] Starting buffering for d6897198-4ca2-433f-b270-215887add16f:f30beaac18944f758fddf09f3fc2daf7
[I 17:20:26.910 NotebookApp] Kernel restarted: d6897198-4ca2-433f-b270-215887add16f
[I 17:20:27.007 NotebookApp] Restoring connection for d6897198-4ca2-433f-b270-215887add16f:f30beaac18944f758fddf09f3fc2daf7
[I 17:20:28.000 NotebookApp] Replaying 3 buffered messages
[I 17:21:24.748 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:23:24.670 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:25:24.712 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:27:24.634 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:28:39.207 NotebookApp] Kernel started: b56e28d3-0364-4829-ac3b-307276b13c82, name: python3
[I 17:29:24.634 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:31:33.433 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:32:33.770 NotebookApp] Starting buffering for b56e28d3-0364-4829-ac3b-307276b13c82:315017f8777e429cbf291fad3e46168a
[I 17:33:35.788 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:35:35.781 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:37:35.812 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:39:35.758 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:41:19.587 NotebookApp] Starting buffering for d6897198-4ca2-433f-b270-215887add16f:f30beaac18944f758fddf09f3fc2daf7
[I 17:41:20.237 NotebookApp] Kernel restarted: d6897198-4ca2-433f-b270-215887add16f
[I 17:41:20.400 NotebookApp] Restoring connection for d6897198-4ca2-433f-b270-215887add16f:f30beaac18944f758fddf09f3fc2daf7
[I 17:41:21.383 NotebookApp] Replaying 3 buffered messages
[I 17:41:35.778 NotebookApp] Saving file at /trigger_test.ipynb
[I 17:43:35.763 NotebookApp] Saving file at /trigger_test.ipynb
